### PR TITLE
Updated encryptor.py and decryptor.py

### PR DESCRIPTION
**Pull request by marvhus**
- Updated src/modules/encryptor.py --- Changed findFiles function
--- Changed encrypt function
--- Changed encryptor function

- Updated src/modules/decryptor.py --- Changed findFiles function
--- Changed decrypt function
--- Changed decryptor function

Note:
I didn't test this code,
since I am scared of messing something up... again, 
but it should work.

So if something is broken, just tell me, and I'll fix it.

### CODE REVIEW

**Comment by ItsJustShepherd** [comment]
I'll run it on a virtual machine to test before merging, but thank you!

**Comment by ItsJustShepherd** [comment]
• lisdir error on line 15.
• When line 15 error resolved `NameError: name 'filePath' not defined` prints with no changes to files being made.

**Comment by marvhus** [comment]
> • lisdir error on line 15. • When line 15 error resolved `NameError: name 'filePath' not defined` prints with no changes to files being made.

which file?

**Comment by marvhus** [comment]
I see the bug.. but not on a line 15

**Comment by marvhus** [comment]
did that fix it @ItsJustShepherd

**Comment by ItsJustShepherd** [comment]
image

• Line 15 `lsdir(path):` when resolved and then the encryptor.py program is ran again you get `NameError: name 'filePath' not defined`


I'll take a look at the new changes, and see if I can get that running in the VM.

**Comment by ItsJustShepherd** [comment]
I made changes on line 15, and ran it through after generating a new key and it seems to work perfectly now.
 Will merge.

**Comment by marvhus** [comment]
... you closed it

**Comment by marvhus** [comment]
oh lol

**Comment by ItsJustShepherd** [comment]
I clicked the wrong button, my bad! 😂

**Pull request merged**
